export const ACTION = {
    // Actions für OpenTrade
    DELETETRADE: "DELETETRADE",
    CREATETRADE: "CREATETRADE",
    GETUPDATETRADE: "GETUPDATETRADE",
    UPDATETRADE: "UPDATETRADE",
    SETUPDATETRADENULL: "SETUPDATETRADENULL",
    TOGGLEMODALCREATEDTRADE: "TOGGLEMODALCREATEDTRADE",
    TOGGLESIDEBAR: "TOGGLESIDEBAR",
    FETCH_ERROR: "FETCH_ERROR",
    FETCH_SUCCESS: "FETCH_SUCCESS",
    // Actions für OpenTrade
    
    // Actions für StrategieTrade
    TOGGLEMODALSTRATEGIETRADE: "TOGGLEMODALSTRATEGIETRADE",
    SETSTRATEGIETRADE: "SETSTRATEGIETRADE",

    // Actions für StrategieTrade
    TOGGLEMODALGOMARKETTRADE: "TOGGLEMODALGOMARKETTRADE",
    TOGGLEMODALGOMARKETONVISTA: "TOGGLEMODALGOMARKETONVISTA",
    SETGOMARKETTRADE: "SETGOMARKETTRADE",

    // Actions für ClosedTrade
    TOGGLEMODALCLOSEDTRADE: "TOGGLEMODALCLOSEDTRADE",
    SETCLOSEDTRADE: "SETCLOSEDTRADE",

    // Actions für Login
    SETDEPOT: "SETDEPOT",
    SETLOGIN: "SETLOGIN",
    TOGGLELOGIN: "TOGGLELOGIN",
}